apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: leesah-tulleapp
  namespace: leesah-quiz
  labels:
    team: leesah-quiz
spec:
  image: {{ image }}
  port: 8080
  strategy:
    type: Recreate
  replicas:
    max: 1
    min: 1
  kafka:
    pool: nav-dev
  env:
    - name: QUIZ_TOPIC
      value: "leesah-quiz.leesah-rapid-v2"
